apiVersion: v1
kind: Service
metadata:
  name: couchdb-external
  labels:
    app: couchdb
spec:
  selector:
    app: couchdb
  type: "LoadBalancer"
  ports:
  - name: data
    port: 5984
  - name: admin
    port: 5986
